// swift-tools-version: 6.0

import PackageDescription

let libsshSources = [
    "Sources/CLibSSH/placeholder.c",
    "Vendor/libssh/src/agent.c",
    "Vendor/libssh/src/auth.c",
    "Vendor/libssh/src/base64.c",
    "Vendor/libssh/src/bignum.c",
    "Vendor/libssh/src/buffer.c",
    "Vendor/libssh/src/callbacks.c",
    "Vendor/libssh/src/channels.c",
    "Vendor/libssh/src/client.c",
    "Vendor/libssh/src/config.c",
    "Vendor/libssh/src/config_parser.c",
    "Vendor/libssh/src/connect.c",
    "Vendor/libssh/src/connector.c",
    "Vendor/libssh/src/crypto_common.c",
    "Vendor/libssh/src/curve25519.c",
    "Vendor/libssh/src/curve25519_crypto.c",
    "Vendor/libssh/src/dh-gex.c",
    "Vendor/libssh/src/dh.c",
    "Vendor/libssh/src/dh_crypto.c",
    "Vendor/libssh/src/ecdh.c",
    "Vendor/libssh/src/ecdh_crypto.c",
    "Vendor/libssh/src/error.c",
    "Vendor/libssh/src/external/bcrypt_pbkdf.c",
    "Vendor/libssh/src/external/blowfish.c",
    "Vendor/libssh/src/external/libcrux_mlkem768_sha3.c",
    "Vendor/libssh/src/external/sntrup761.c",
    "Vendor/libssh/src/getpass.c",
    "Vendor/libssh/src/getrandom_crypto.c",
    "Vendor/libssh/src/gzip.c",
    "Vendor/libssh/src/hybrid_mlkem.c",
    "Vendor/libssh/src/init.c",
    "Vendor/libssh/src/kdf.c",
    "Vendor/libssh/src/kex.c",
    "Vendor/libssh/src/known_hosts.c",
    "Vendor/libssh/src/knownhosts.c",
    "Vendor/libssh/src/legacy.c",
    "Vendor/libssh/src/libcrypto.c",
    "Vendor/libssh/src/log.c",
    "Vendor/libssh/src/match.c",
    "Vendor/libssh/src/md_crypto.c",
    "Vendor/libssh/src/messages.c",
    "Vendor/libssh/src/misc.c",
    "Vendor/libssh/src/mlkem.c",
    "Vendor/libssh/src/mlkem_crypto.c",
    "Vendor/libssh/src/options.c",
    "Vendor/libssh/src/packet.c",
    "Vendor/libssh/src/packet_cb.c",
    "Vendor/libssh/src/packet_crypt.c",
    "Vendor/libssh/src/pcap.c",
    "Vendor/libssh/src/pki.c",
    "Vendor/libssh/src/pki_container_openssh.c",
    "Vendor/libssh/src/pki_context.c",
    "Vendor/libssh/src/pki_crypto.c",
    "Vendor/libssh/src/pki_ed25519_common.c",
    "Vendor/libssh/src/poll.c",
    "Vendor/libssh/src/scp.c",
    "Vendor/libssh/src/session.c",
    "Vendor/libssh/src/sftp.c",
    "Vendor/libssh/src/sftp_aio.c",
    "Vendor/libssh/src/sftp_common.c",
    "Vendor/libssh/src/sntrup761.c",
    "Vendor/libssh/src/socket.c",
    "Vendor/libssh/src/string.c",
    "Vendor/libssh/src/threads.c",
    "Vendor/libssh/src/threads/libcrypto.c",
    "Vendor/libssh/src/threads/noop.c",
    "Vendor/libssh/src/threads/pthread.c",
    "Vendor/libssh/src/token.c",
    "Vendor/libssh/src/ttyopts.c",
    "Vendor/libssh/src/wrapper.c",
]

let package = Package(
    name: "SSHKit",
    platforms: [
        .iOS(.v13),
        .macOS(.v10_15),
        .macCatalyst(.v13),
        .tvOS(.v13),
        .visionOS(.v1),
    ],
    products: [
        .library(name: "SSHKit", type: .dynamic, targets: ["SSHKit"]),
        .library(name: "SSHKitObjC", type: .dynamic, targets: ["SSHKitObjC"]),
        .library(name: "CLibSSH", type: .dynamic, targets: ["CLibSSH"]),
    ],
    dependencies: [
        .package(url: "https://github.com/Lakr233/openssl-spm.git", from: "3.6.0"),
        .package(url: "https://github.com/kishikawakatsumi/KeychainAccess.git", from: "4.2.2"),
    ],
    targets: [
        .target(
            name: "CLibSSH",
            dependencies: [
                .product(name: "OpenSSL", package: "openssl-spm"),
            ],
            path: ".",
            sources: libsshSources,
            publicHeadersPath: "Sources/CLibSSH/include",
            cSettings: [
                .headerSearchPath("Sources/CLibSSH/include"),
                .headerSearchPath("Vendor/libssh/src"),
                .headerSearchPath("Vendor/libssh/src/external"),
            ],
            linkerSettings: [
                .linkedLibrary("z"),
            ],
        ),
        .target(
            name: "SSHKitObjC",
            dependencies: ["CLibSSH"],
            path: "Sources/SSHKitObjC",
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("Private"),
            ],
            linkerSettings: [
                .linkedFramework("Security"),
            ],
        ),
        .target(
            name: "SSHKit",
            dependencies: [
                "SSHKitObjC",
                .product(name: "KeychainAccess", package: "KeychainAccess"),
            ],
            path: "Sources/SSHKit",
            swiftSettings: [
                .swiftLanguageMode(.v5),
            ],
        ),
        .testTarget(
            name: "SSHCoreObjCTests",
            dependencies: ["SSHKitObjC"],
            path: "Tests/SSHCoreObjCTests",
            cSettings: [
                .headerSearchPath("../../Sources/SSHKitObjC/Private"),
            ],
        ),
        .testTarget(
            name: "SSHKitTests",
            dependencies: ["SSHKit"],
        ),
        .testTarget(
            name: "LiveSSHTests",
            dependencies: ["SSHKit"],
        ),
    ],
    cLanguageStandard: .c11,
)
